"""remove_mode_col

Revision ID: 4c42491aed1d
Revises: 
Create Date: 2022-02-11 22:52:07.488835

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c42491aed1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bot_store',
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('lang', sa.Integer(), nullable=True),
        sa.Column('processed_dttm', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_store')
    # ### end Alembic commands ###
